### ISSUE TITLE
memory dependency

### ISSUE THREAD

**Issue by arybczak** [apotheca/botan#1]
Hey,

I think it would be nice if the library used ByteStringS instead of `memory`. Any particular reason you chose to use it? IIUC `memory` suffers from similar fate other Vincent's libraries do.

**Comment by ldillinger** [comment]
Oh, I did not even realize! For some reason, I thought that it was a either a boot or a core library.

That is a shame, because I rather like using things like `ByteArray` for constant-time equality and `ScrubbedBytes` for haskell cryptography, and also because its a fair bit easier than dealing with `Bits` (which, in my opinion, is second only to `Num` when it comes to badly-designed typeclasses). I am uninformed as to the particulars of what transpired, but he is certainly leaving a cannonball-sized hole in the Haskell ecosystem, isn't he?

On the other hand, this indicates both a need for replacements for these things, and there is the potential to fill some of them via these bindings - Botan *does* does have have functions for *many* of the constructs provided by `memory` which are useful for cryptography, including:

- Constant-time equality checks
- SipHash
- Base16 and Base64 encoding

I also definitely think that the `ScrubbedBytes` class is worth saving, though probably as part of higher-level bindings layer later.

I will axe the `memory` dependency :)

**Comment by ldillinger** [comment]
Err, clicked the wrong button, this will be closed next update.

**Comment by ldillinger** [comment]
Now it is closed.
