### ISSUE TITLE
Documentation readability suggestion

### ISSUE THREAD

**Issue by Vlix** [apotheca/botan#11]
https://github.com/apotheca/botan/blob/72efa8573d3aac91e14001ef79164d5cf89d1244/botan-bindings/src/Botan/Bindings/Bcrypt.hs#L44

This is weird to read: `password the password` cf. [haddock reference](https://hackage.haskell.org/package/botan-bindings-0.0.1.0/candidate/docs/Botan-Bindings-Bcrypt.html#v:botan_bcrypt_generate)

Could I recommend formatting it more like:

```hs
 -> ConstPtr CChar -- ^ @password@: the password
```

**Comment by ldillinger** [comment]
This suggestion has been applied and will be in the coming release update.

**Comment by Vlix** [comment]
Everywhere, or only in the `Bcrypt` module?
(I noticed it's like this in a lot of modules)

**Comment by ldillinger** [comment]
Everywhere! In `botan-bindings` and `botan-low`. I did have to go with `__varname__` instead of `@varname@` because the monospace was taking up gobs of extra height if it was the only content:

<img width="444" alt="Screenshot 2024-02-13 at 2 26 08 PM" src="https://github.com/apotheca/botan/assets/43178839/f4c55be5-3c76-4e7a-8a7c-335e72ea217e">

So I went with bold instead.
